# port to open a request on
port = 5001
# host to open a request on
host = "127.0.0.1"


## server configurations
#[servers.main]
#host = "127.0.0.1"
#port = 8000
#name = "main"
#
#[servers.backup1]
#host = "127.0.0.1"
#port = 8001
#name = "backup"
